version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/k8s"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "yarn"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
