# fly.toml app configuration file generated for penn-clubs-frontend on 2023-09-01T14:14:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "penn-clubs-frontend"
primary_region = "ewr"

# [build]
#   image = "pennlabs/penn-clubs-frontend:latest"

[env]
  DOMAIN = "upenn.club"

[http_service]
  internal_port = 3000
  force_https = false # TODO: eventually true lmao
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
