# fly.toml app configuration file generated for clubs-backend on 2023-09-01T14:48:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "clubs-backend"
primary_region = "ewr"

[env]
  # TODO: On fly, the REDIS_URL should not end with trailing `/1`.
  DOMAINS = "*" # TODO: not sure why but was `*` before

[http_service]
  internal_port = 80
  force_https = false # TODO: eventually true lmao
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
