# fly.toml app configuration file generated for redis-clubs on 2023-09-14T21:50:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "redis-clubs"
primary_region = "ewr"

[build]
  image = "redis:7.2.1"

[[mounts]]
  source = "redis_clubs"
  destination = "/data"

[metrics]
  port = 9091
  path = "/metrics"
